spring:
  datasource:
    url: jdbc:h2:file:./db-temp/maindb;AUTO_SERVER=TRUE

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: validate

    generate-ddl: true
    show-sql: false

    properties:
      hibernate:
        format_sql: true
        default_schema: OTUS_HW_06
        type: TRACE
        use_sql_comments: true
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true
        show_sql: false

  sql:
    init:
      mode: always

logging:
  config: classpath:/logback-spring.xml
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: TRACE