= Домашнее задание №6

Переписать приложение для хранения книг на ORM

== Цель

Полноценно работать с `JPA` + `Hibernate` для подключения к реляционным БД посредством `ORM`-фреймворка

== Ожидаемый результат

Высокоуровневое приложение с `JPA`-маппингом сущностей.

== Описание/пошаговая инструкция выполнения домашнего задания

Домашнее задание выполняется переписыванием предыдущего _(ДЗ №5)_ на `JPA`.

=== Детализированные требования

. Использовать `JPA`, `Hibernate` только в качестве `JPA`-провайдера
. Загрузка связей сущностей не должна приводить к большому количеству запросов к БД или избыточному по объему набору данных (проблема N+1 и проблема произведения таблиц)
. Добавить сущность `<комментария к книге>`, реализовать `CRUD` для новой сущности. Получение всех комментариев делать не нужно. Только конкретного комментария по `id` и всех комментариев по конкретной книге по ее `id`.
. `DDL` через `Hibernate` должно быть отключено.
. `LAZY`-связи не должны присутствовать в `equals/hashCode/toString` (в т.ч. за счет `@Data`).
. Аннотация `@Transactional` должна присутствовать только на методах сервиса.
. Покрыть репозитории тестами, используя `H2` базу данных и `@DataJpaTest`.
. Написать интеграционные тесты сервисов книг и комментариев, которые будут проверять работу с БД. Транзакционность в этих тестах должна быть отключена, чтобы не влияла на транзакции в сервисах. Проверить, что доступ к связям, которые используются снаружи сервисов не вызывают `LazyInitialzationException`. Не забыть учесть кэширование контекста в тестах.
. Добавить в решение тесты из заготовки: https://github.com/OtusTeam/Spring/tree/master/templates/hw06-jpa[ссылка]. Для приема работы тесты должны проходить.

CAUTION: `Spring Data` пока использовать нельзя.